apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- hpa.yaml
- configmap.yaml
secretGenerator:
- literals:
  - secret=546789
  name: node-express-realworld-example-api-service-secrets
  type: Opaque
generatorOptions:
  disableNameSuffixHash: true
